/*const admin = require('firebase-admin');
const functions = require('firebase-functions');

admin.initializeApp(functions.config().firebase);

exports.createUID = functions.https.onRequest((request, response) => {
  //const text = request.query.text; //takes text message
  const resp = request.body.name; // GET request use query; POST request body
  const a = request.body.data;


  writeUserData() {
    var createID = firebase.database().ref('/workout_sessions').push();
    var retrieveID = createID.key();

    var workoutSessions = {
      session_id: retrieveID
    }

    myRef.push(workoutSessions);

  }


  //connects to the firebase database
  admin
    .database()
    .ref('/workout_sessions') // connection under refrense workout_sessions
    postsRef.push() //push unique id
    // response with a message
    .then(()


    })



// Generate a reference to a new location and add some data using push()
var newPostRef = postsRef.push();

// Get the unique key generated by push()
var postId = newPostRef.key;

*/
